<?php
include ("dbconfig.php");
include ("db.php");
include ("invoicedataclass.php");
$db1= new dbclass();
$db1->connect();
$invoiceno=$_REQUEST['invoice_no'];
$invoicedata1=new invoicedataclass();
$invoicedata1->displayinvoice($invoiceno);

echo $invoicedata1->invoicedate1;
echo $invoicedata1->selectcustomer1;
echo $invoicedata1->selectvehicle1;
echo $invoicedata1->nameofinsurancepolicy1;
echo $invoicedata1->insurancepolicyno1;
echo $invoicedata1->expirydate1;
echo $invoicedata1->insuranceagent1;
echo $invoicedata1->phoneno1;
echo $invoicedata1->isdealerguaranty1;
echo $invoicedata1->dealerguarantydescription1;
echo $invoicedata1->isthirdpartywarranty1;
echo $invoicedata1->retailpriceifincludedinsellingprice1;
echo $invoicedata1->company1;
echo $invoicedata1->thirdpartywarrantydescription1;
echo $invoicedata1->sellingprice1;
echo $invoicedata1->administrationfees1;
echo $invoicedata1->tradeinallowance1;
echo $invoicedata1->licencefees1;
echo $invoicedata1->gasoline1;
echo $invoicedata1->payoutlienontradein1;
echo $invoicedata1->gsthstpayableontradein1;
echo $invoicedata1->depositmadeby1;
echo $invoicedata1->depositamount1;
echo $invoicedata1->amountpayableondelivery1;
echo $invoicedata1->insurance1;
echo $invoicedata1->insuranceamount1;
echo $invoicedata1->pstoninsurance1;
echo $invoicedata1->lienregistrationfees1;
echo $invoicedata1->balancefinanced1;
echo $invoicedata1->netamounttobefinanced1;
echo $invoicedata1->costofborrowing1;
echo $invoicedata1->amountofpayments1;
echo $invoicedata1->noofpayments1;
echo $invoicedata1->paymentstartson1;
echo $invoicedata1->creditapproval1;
echo $invoicedata1->dealerreceiveincentive1;
echo $invoicedata1->nondisclosurestatementdetails1;
echo $invoicedata1->canadianmotorvehiclearbplan1;
echo $invoicedata1->salespersonname1;
echo $invoicedata1->salespersonsregistrationno1;
echo $invoicedata1->dealersregistrationno1;
echo $invoicedata1->dealersnameofofficial1;
echo $invoicedata1->acceptorsregistrationno1;
echo $invoicedata1->acceptorstitle1;
echo $invoicedata1->accepteddate1;
?>